## Homework 1
### Due Tuesday September 17, 11:59 PM

### Collaboration Policy

While you may talk with others about
the homework, we ask that you **write your solutions individually**. If you do
discuss the assignments with others please **include their names** at the top
of your notebook. 

**Collaborators**: *list collaborators here*

### Goal

Homework 1 will help prepare you for class along with the other assignments. The problems will review some of the programming that we will need throughout the semester. Please check the references for more information on unfamiliar material. Reach out to us in section and office hours for help. 

**Tips** To learn about keyboard shortcuts, go to **Help -> Keyboard Shortcuts** in the menu above. Get help for a function by running a cell with the function name and a `?` at the end...you can escape by hitting ```esc``` several times.  Alternatively type the function name, then <Shift>-<Tab> on your keyboard...you can press <Tab> multiple times to show additional information.

### Score Breakdown
Question | Points
--- | ---
1 | 2
2a | 1
2b | 1
2c | 2
2d | 2
3a | 3
3b | 3
4a | 2
4b | 2
4c | 3
4d | 3
Total | 24

### Question 1
Recall that summation (or sigma notation) is a way of expressing a long sum in a concise way.  Let $a_1, a_2, ..., a_n \in \mathbb{R}$ and $x_1, x_2, ..., x_n \in \mathbb{R}$ be collections of real numbers.  When you see $x_i$, you can think of the $i$ as an index for the $i^{th}$ $x$.  For example $x_2$ is the second $x$ value in the list $x_1, x_2, ..., x_n$.  We define sigma notation as follows:

$$ \sum_{i=1}^n a_i x_i = a_1 x_1 + a_2 x_2 + ... + a_n x_n $$
	
We commonly use sigma notation to compactly write the definition of the arithmetic mean (commonly known as the ``average``):
	
$$ \bar{x} = \dfrac{1}{n} \left(x_1 + x_2 + ... + x_n \right) = \dfrac{1}{n} \sum_{i=1}^{n} x_i $$

Recall the formula for population variance below:

$$\sigma^2 = \frac{\sum_{i=1}^N (x_i - \mu)^2}{N}$$

Complete the functions below to compute the population variance of `population`, an array of numbers. For this question, do not use built in NumPy functions; we will use NumPy to verify your code.

In [1]:
import numpy as np

In [2]:
def mean(population):
    """
    Returns the mean of population (mu)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    # Calculate the mean of a population
    sum = 0
    for i in range(len(population)):
        sum = sum + population[i]
    
    total = sum / len(population)
    return total
   

def variance(population):
    """
    Returns the variance of population (sigma squared)
    
    Keyword arguments:
    population -- a numpy array of numbers
    """
    average = mean(population)
    sum = 0
    for i in range(len(population)):
        sum = sum + ((population[i] - average) ** 2)
    total = sum / len(population)
    return total

Run the following cell to test your function against ```numpy```

In [3]:
# TEST
population_0 = np.random.randn(100)
np.isclose(mean(population_0), np.mean(population_0), atol=1e-6)

True

In [4]:
# TEST
population_0 = np.random.randn(100)
np.isclose(variance(population_0), np.var(population_0), atol=1e-6)

True

### Question 2

Suppose you're trying to meet your friend in either Central Park (denoted C) or Riverside Park (denoted R). 

Right now, you know that the chances of your friend being at $z$ are

| &nbsp; | Chance |
| --- | --- | 
| **z = Central Park** | 0.6 |
| **z = Riverside Park** | 0.4 | 

a. Use ```numpy``` to create a $2 \times 1$ array called ```v``` with chance of being in Central Park and Riverside Park. Try testing the dimensions.

In [5]:
# BEGIN SOLUTION
v = np.array([0.6, 0.4])
# TODO: solve me
# END SOLUTION

# TEST
v.shape

(2,)

Since your friend like to wander around, you know that after 1 hour the chances of her walking from $x$ to $y$ are   

| &nbsp; | x = Central Park | x=  Riverside Park |
| --- | --- | --- |
| **y = Central Park** | 0.6 | 0.7 |
| **y = Riverside Park** | 0.4 | 0.3 |

b. Use ```numpy``` to create a $2 \times 2$ matrix ```M``` with chance of walking between parks. Try testing the dimensions.

In [6]:
# BEGIN SOLUTION
m = np.array([[.6, .7], [.4, .3]])
print(m)
# TODO: solve me
# END SOLUTION
m.shape

[[0.6 0.7]
 [0.4 0.3]]


(2, 2)

c. Use the ```numpy``` sum method to sum the entries over columns. Do the entries sum to 1 -- why?

Use the ```numpy``` sum method to sum the entries over rows. Do the entries sum to 1 -- why?

In [7]:
# BEGIN SOLUTION
#Summing over Rows
rows = m.sum(axis=1)

#Summing over Columns
columns = m.sum(axis=0)

print(rows)
print(columns)
# TODO: solve me
# END SOLUTION

[1.3 0.7]
[1. 1.]


The columns sum to 1 because if starting at x, there are only 2 options: stay in the current park or move to another park. These two options must sum up to 1 because you either stay or move to another park. 

The rows do not sum to 1 because the rows assume you start at y. 

d. Use the Law of Total Probability to determine the likelihood that your friend is in Central Park or Riverside Park after 1 hour. 

**Hint: Use the @ symbol for multiplication**

In [8]:
# BEGIN SOLUTION

#A = Start in Central Park
#B = Start in Riverside Park

matrix = np.array([[v[0] * (m[:,0])], [v[1] * (m[:,1])]])
print(matrix)
sums = matrix.sum(axis=0)
print("The probability that my friend is in Central Park after 1 hour is: ", sums[0][0])
print("The probability that my friend is in Riverside Park after 1 hour is: ", sums[0][1])

# TODO: solve me
# END SOLUTIONt

[[[0.36 0.24]]

 [[0.28 0.12]]]
The probability that my friend is in Central Park after 1 hour is:  0.6399999999999999
The probability that my friend is in Riverside Park after 1 hour is:  0.36


### Question 3

a. Debugging is jargon for inspecting the code in a program line by line for errors. Try inspecting the following code -- locate, document and correct each error.

In [3]:
# Write a program that will average 3 numeric exam grades, return an average test score, a corresponding letter grade, and a message stating whether the student is passing.

# Average	Grade
# 90+	A
# 80-89	B
# 70-79	C
# 60-69	D
# 0-59	F

exam_one = int(input("Input exam grade one: "))

#Without casting exam_two as an int, it would remain as a string
exam_two = int(input("Input exam grade two: "))

#exam_3 was casted as a string, not int
#Also, exam_3 should be renamed exam_three to keep consistent with the other variable names
exam_three = int(input("Input exam grade three: "))

#Need commas to separate each element in a list
grades = [exam_one, exam_two, exam_three]
sum = 0

#for grade is grades
for grade in grades:
    sum = sum + grade

#typo for grades: should be "grades", not "grdes"
avg = float(sum / len(grades))
avg = round(avg)

if avg >= 90:
    letter_grade = "A"
#There should be parentheses around the boolean statements and the following line is missing a colon
elif (avg >= 80 and avg < 90):
    letter_grade = "B"
elif avg > 69 and avg < 80:

#The letter_grade is "C' but it should be "C": need to match quotations
    letter_grade = "C"
elif avg <= 69 and avg >= 65:
    letter_grade = "D"
    
#Should be else not elif
else:
    letter_grade = "F"

print("Exams:" + str(exam_one) + ", " + str(exam_two) + ", " + str(exam_three))
print("Average: " + str(round(avg)))
print("Grade: " + letter_grade)

if letter_grade is "F":
    
#missing parentheses
    print ("Student is failing.")
else:

#missing parenthesis
    print ("Student is passing.")

Input exam grade one:  89
Input exam grade two:  90
Input exam grade three:  90


90
Exams:89, 90, 90
Average: 90
Grade: A
Student is passing.


In [ ]:
# TEST 1 
# Exams: 89, 90, 90
# Average: 90
# Grade: A
# Student is passing.

# TEST 2
# Exams: 50, 51, 0
# Average: 33
# Grade: F
# Student is failing.

b. We can use debugging tool to explore the state of a running program without using print() statements everywhere. In Jupyter notebooks, we can import the ```pdb``` package for the debugger.

In [4]:
import pdb

We can use the debugger in two ways: 

1. After the code threw an exception, we work **backwards** from the problem. 
 * Run ```pdb.pm()``` to start the debugger after an exception. 
 * Use the ```up``` command to work backwards. 
 * Use ```quit``` to quit the debuggger. 

2. We place a **break-point** where execution halts and we work **forwards** line by line. 
 * Place ```pdb.set_trace()``` in the line where execution should halt. 
 * Try using the following to work forwards.
    1. `list` - Displays 11 lines around the current line or continue the previous listing.
    2. `step` - Execute the current line, stop at the first possible occasion.
    3. `next` - Continue execution until the next line in the current function is reached or it returns.
    4. `break` - Set another breakpoint at a line (depending on the argument provided).
    5. `return` - Continue execution until the current function returns.
   
 * For more information type `help` 


Save the following script to a file called ```fib.py```.

```python 
# fib.py

import sys

def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

for i in range(len(sys.argv)):
    arg = sys.argv[i]
    num = int(arg)
    print("fib of", num, " = ", fib(num))
```

Try executing the following in a cell

```python 
%run fib.py 4 5 6
```

In [7]:
#The first argument is the name of the file, so it cannot be passed into the function. Skipping the first index will allow the program to run. 

%run fib.py 4 5 6

fib of 4  =  3
fib of 5  =  5
fib of 6  =  8


What went wrong...use ```pdb``` to locate, document and correct the errors in ```fib.py```.

### Question 4

Consider the following scenario:

Only $1\%$ of 40-year-old women who participate in a routine mammography test have breast cancer. $80\%$ of women who have breast cancer will test positive, but $9.6\%$ of women who don’t have breast cancer will also get positive tests. 

a. Fill in the conditional probability table 

| &nbsp; | x = Has Cancer | x=  Does Not Have Cancer |
| --- | --- | --- |
| **Tested Positive given x** | .8 | .096 |
| **Tested Negative given x** | .2 | .904 |

**SOLUTION:**


---------------

b. Fill in the joint probability table 

| &nbsp; | Has Cancer | Does Not Have Cancer |
| --- | --- | --- |
| **Tested Positive** | .008 | .095 |
| **Tested Negative** | .002 | .895 |

**SOLUTION:**


---------------

c. Suppose we know that a woman of this age tested positive in a routine screening. What is the probability that she actually has breast cancer?

**Hint:** Use Bayes' rule.

**SOLUTION:**
100 out of 10,000 women have breast cancer. 80% of those women have breast cancer, so 80 women. 9.6% of the 9900 who do not have breast cancer will test positive, so that is 950 women. 950 women who test positive though do not have breast cancer + 80 women who do have breast cancer and test positive = 1030 women. 80/1030 = 7.78%.

---------------

d. Sometimes, 40-year-old men will also get mammographies, if they are suspected to be at high risk to breast cancer. The overall prevalence of breast cancer in men who participate in the test is lower (0.01%). As with women, 80% of men who have breast cancer will test positive. Due to physiological diferences, only 2.4% of men who don't have breast cancer will test positively.

For each of the following pairs of events $A$ and $B$, please determine whether or not they are independent:

1. $A$ = the subject's sex (man or woman), $B$ = having breast cancer.
2. $A$ = the subject's sex, $B$ = testing positively for breast cancer given having breast cancer.
3. $A$ = the subject's sex, $B$ = testing positively for breast cancer.

**Hint:** Events $A$ and $B$ are independent if $P(B \mid A) = P(B)$

**SOLUTION:**
1. Dependent: Because men who participate in a test have a .01% of having breast cancer and women who participate in a test have a 1% chance, this event is dependent on gender because women have a higher chance of having breast cancer overall.
2. Independent: Because both men and women who have breast cancer have an equal chance (80%) of testing positive, this event is independent. 
3. Dependent: Men who do not have breast cancer have a 2.4% probability of testing positively, while women have a 9.6% chance of testing positive even if they do not have breast cancer. This event is dependent on gender because the probabilities are different. 
---------------